---
title: "SQL Database"
output: html_document
---

<link href="style/styles.css" rel="stylesheet">

## Working with SQL database in R
### [DBI and odbc](https://db.rstudio.com/getting-started/connect-to-database) pacakges are used in connecting an existing database.


- ####Using credentials to create a MS SQL connection - called 'con' -
```{r eval=F }
library(DBI)
con <- dbConnect(odbc::odbc(), driver = "ODBC Driver 13 for SQL Server", 
                 server = "database server name", Database = "database name", 
                 uid = "your database username", 
                 pwd = "your database password")
```

- ####Querying database data with SQL queries
```{r eval=F}
dbGetQuery(conn = con,statement = 'your SQL statement query')
```

- ####Writing a in-memory data frame to a database table 
```{r eval=F}
# writing a new datatable in SQL server database
dbWriteTable(conn = con,name = 'your new table name',value = 'dataframe name')   
# Overwriting the exiting database table
dbWriteTable(conn = con,name = 'your exiting table name',value = 'dataframe name', overwrite = TRUE) 
# Appending dataframe into the exiting database table
dbWriteTable(conn = con,name = 'your exiting table name',value = 'dataframe name', append = TRUE)
```

- ####Closing the connection if needed
```{r eval=F}
dbDisconnect(conn = con)
```
 
### for more functions available in DBI, check [here](http://dbi.r-dbi.org/reference/)

